version: "2.2"
services:
  gpiod:
    # https://gpiozero.readthedocs.io/en/stable/remote_gpio.html
    image: corbosman/pigpiod
    # build: "./gpiod"
    privileged: true
    restart: unless-stopped
    networks:
      - primarynet

  # psitransfer:
  #   image: psitrax/psitransfer
  #   container_name: psitransfer
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - PSITRANSFER_ADMIN_PASS=codeclub
  #   ports:
  #     - 3500:3500
  #   volumes:
  #     - ./uploads:/data

  # gotify: # no arm build availible
  #   container_name: gotify
  #   image: gotify/server
  #   restart: unless-stopped
  #   volumes:
  #     - ./codeclub/gotify/data:/app/data
  #   ports:
  #     - "8500:80"

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./codeclub/heimdall:/config
    ports:
      - 8081:80
      # - 443:443
    restart: unless-stopped
    networks:
      - primarynet

  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/London
      - SUBDOMAINS=codeclub  #,subdomain2
      - TOKEN=fca54c9a-696d-4d01-99aa-f937204bce62
      - LOG_FILE=false #optional
    # volumes:
    #   - /path/to/appdata/config:/config #optional
    restart: unless-stopped

  # transfer:
  #   image: dutchcoders/transfer.sh:latest 
  #   containername: transfersh 
  #   volumes:
  #     - ./altuploads:/tmp/
  #   command: "--provider local --basedir /tmp/"

  # raspap:
  # build: ".Dockerfile-raspap"
  # ports:
  #   - "80:80"
  #   - "100:100"
  # restart: unless-stopped

  mongodb:
    image: 'arm64v8/mongo'
    restart: unless-stopped
    container_name: mongodbcc
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    expose:
      - "27017"
      - "28017"
    command: "mongod --bind_ip_all --logpath=/dev/null"
    networks:
      - primarynet

  redis:
    image: redis
    container_name: cache
    expose:
      - "6379"
    networks:
      - primarynet

networks:
  primarynet:
    name: service_net


    ################## commented out stuff ###############
  # nodered:
  #   image: nodered/node-red
  #   volumes:
  #       - ./codeclub/nodered:/data
  #   ports:
  #       - "1880"
  #   environment: 
  #     - REDIS_URL=redis://cache
  #   scale: 3
  #   restart: unless-stopped
  #   # networks:
  #   #   - primarynet

  # nginxnr:
  #   image: nginx:latest
  #   restart: always
  #   container_name: nginxnr
  #   volumes:
  #     - ./noderedcompose/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - nodered
  #   ports:
  #     - "9998:80"
